name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install
        run: |
          pip install poetry
          poetry install
      - name: lint
        run: poetry run make lint